Repository go-vela/community, pull requests merged in 2021-08, with the labels that each got.

#338 feat(v0.9): add initial migration framework
  migrations/v0.9/DOCS.md
  migrations/v0.9/Dockerfile
  migrations/v0.9/Makefile
  migrations/v0.9/README.md
  migrations/v0.9/go.mod
  migrations/v0.9/go.sum
  migrations/v0.9/main.go
  migrations/v0.9/run.go
Labels: feature

#339 feat(proposals/2021): add log streaming information
  proposals/2021/07-22_log-streaming.md
  proposals/2021/README.md
  proposals/README.md
Labels: feature, area/server, area/worker, status/in-progress

#362 chore(releases/v0.9): add v0.9.0 migration utility
  migrations/README.md
  migrations/v0.9/DOCS.md
  migrations/v0.9/Makefile
  migrations/v0.9/README.md
  migrations/v0.9/alter.go
  migrations/v0.9/database.go
  migrations/v0.9/exec.go
  migrations/v0.9/go.mod
  migrations/v0.9/go.sum
  migrations/v0.9/main.go
  migrations/v0.9/run.go
  migrations/v0.9/validate.go
Labels: enhancement
