Repository go-vela/community, pull requests merged in 2021-01, with the labels that each got.

#154 feat(v0.7.0): add required migration info
  .gitignore
  migrations/README.md
  migrations/v0.7.0/Dockerfile
  migrations/v0.7.0/Makefile
  migrations/v0.7.0/README.md
  migrations/v0.7.0/go.mod
  migrations/v0.7.0/go.sum
  migrations/v0.7.0/main.go
Labels: feature

#171 Rate limiting builds proposal
  proposals/proposal_2020_12_rate-limiting.md
Labels: area/server, discussion

#182 fix: switch dockerfile to make build-static
  migrations/v0.7.0/Dockerfile
Labels: bug

#184 chore: update copyright year to 2021
  LICENSE
  migrations/v0.7.0/Dockerfile
  migrations/v0.7.0/Makefile
  migrations/v0.7.0/main.go
Labels: enhancement
